//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOS_FxApps.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.25;Initial Catalog=gos_apps;Persist Security Info=True;User" +
            " ID=sa;Password=%tii2025%;TrustServerCertificate=True")]
        public string gos_appsConnectionString {
            get {
                return ((string)(this["gos_appsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=\"mssql-200073-0.cloudclusters.net, 16370\";Initial Catalog=gos_apps;Pe" +
            "rsist Security Info=True;User ID=DTIAdmin;Password=%Tii2025%;TrustServerCertific" +
            "ate=True")]
        public string gos_appsConnectionString1 {
            get {
                return ((string)(this["gos_appsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mssql-200510-0.cloudclusters.net,19998;Initial Catalog=gos_apps;Persi" +
            "st Security Info=True;User ID=DTIAdmin;Password=%Tii2025%;TrustServerCertificate" +
            "=True")]
        public string gos_apps {
            get {
                return ((string)(this["gos_apps"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = TII_NB2_1122; Initial Catalog = gos_apps; User ID = tii; Password=m" +
            "m;TrustServerCertificate=True")]
        public string gos_appsserver {
            get {
                return ((string)(this["gos_appsserver"]));
            }
        }
    }
}
